#! /bin/bash
#Run trinity to assemble transcriptome
#Dependency: trinity v2.15.1

TRINITY_SMIG_PATH=/usr/local/biotools/t/trinity:2.15.1--h6ab5fc9_2

singularity exec ${TRINITY_SMIG_PATH} Trinity --seqType fq --max_memory 300G --left \
./filtered/brain_PP1_m_trimmed_1P.fq.gz,./filtered/brain_PP2_f_trimmed_1P.fq.gz,./filtered/brain_PP3_m_trimmed_1P.fq.gz,./filtered/brain_PP4_f_trimmed_1P.fq.gz,./filtered/brain_PP5_m_trimmed_1P.fq.gz,./filtered/brain_PP6_f_trimmed_1P.fq.gz,./filtered/brain_PP7_m_trimmed_1P.fq.gz,./filtered/gill_PP1_m_trimmed_1P.fq.gz,./filtered/gill_PP2_f_trimmed_1P.fq.gz,./filtered/gill_PP3_m_trimmed_1P.fq.gz,./filtered/gill_PP4_f_trimmed_1P.fq.gz,./filtered/gill_PP5_m_trimmed_1P.fq.gz,./filtered/gill_PP6_f_trimmed_1P.fq.gz,./filtered/gill_PP7_m_trimmed_1P.fq.gz,./filtered/gonad_PP1_m_trimmed_1P.fq.gz,./filtered/gonad_PP2_f_trimmed_1P.fq.gz,./filtered/gonad_PP3_m_trimmed_1P.fq.gz,./filtered/gonad_PP4_f_trimmed_1P.fq.gz,./filtered/gonad_PP5_m_trimmed_1P.fq.gz,./filtered/gonad_PP6_f_trimmed_1P.fq.gz,./filtered/gonad_PP7_m_trimmed_1P.fq.gz,./filtered/liver_PP1_m_trimmed_1P.fq.gz,./filtered/liver_PP2_f_trimmed_1P.fq.gz,./filtered/liver_PP3_m_trimmed_1P.fq.gz,./filtered/liver_PP4_f_trimmed_1P.fq.gz,./filtered/liver_PP5_m_trimmed_1P.fq.gz,./filtered/liver_PP6_f_trimmed_1P.fq.gz,./filtered/liver_PP7_m_trimmed_1P.fq.gz,./filtered/pec_musAD_PP1_m_trimmed_1P.fq.gz,./filtered/pec_musAD_PP2_f_trimmed_1P.fq.gz,./filtered/pec_musAD_PP3_m_trimmed_1P.fq.gz,./filtered/pec_musAD_PP4_f_trimmed_1P.fq.gz,./filtered/pec_musAD_PP5_m_trimmed_1P.fq.gz,./filtered/pec_musAD_PP6_f_trimmed_1P.fq.gz,./filtered/pec_musAD_PP7_m_trimmed_1P.fq.gz,./filtered/pit_PP1_m_trimmed_1P.fq.gz,./filtered/pit_PP2_f_trimmed_1P.fq.gz,./filtered/pit_PP3_m_trimmed_1P.fq.gz,./filtered/pit_PP4_f_trimmed_1P.fq.gz,./filtered/pit_PP5_trimmed_1P.fq.gz,./filtered/pit_PP6_f_trimmed_1P.fq.gz,./filtered/pit_PP7_m_trimmed_1P.fq.gz \
--right ./filtered/brain_PP1_m_trimmed_2P.fq.gz,./filtered/brain_PP2_f_trimmed_2P.fq.gz,./filtered/brain_PP3_m_trimmed_2P.fq.gz,./filtered/brain_PP4_f_trimmed_2P.fq.gz,./filtered/brain_PP5_m_trimmed_2P.fq.gz,./filtered/brain_PP6_f_trimmed_2P.fq.gz,./filtered/brain_PP7_m_trimmed_2P.fq.gz,./filtered/gill_PP1_m_trimmed_2P.fq.gz,./filtered/gill_PP2_f_trimmed_2P.fq.gz,./filtered/gill_PP3_m_trimmed_2P.fq.gz,./filtered/gill_PP4_f_trimmed_2P.fq.gz,./filtered/gill_PP5_m_trimmed_2P.fq.gz,./filtered/gill_PP6_f_trimmed_2P.fq.gz,./filtered/gill_PP7_m_trimmed_2P.fq.gz,./filtered/gonad_PP1_m_trimmed_2P.fq.gz,./filtered/gonad_PP2_f_trimmed_2P.fq.gz,./filtered/gonad_PP3_m_trimmed_2P.fq.gz,./filtered/gonad_PP4_f_trimmed_2P.fq.gz,./filtered/gonad_PP5_m_trimmed_2P.fq.gz,./filtered/gonad_PP6_f_trimmed_2P.fq.gz,./filtered/gonad_PP7_m_trimmed_2P.fq.gz,./filtered/liver_PP1_m_trimmed_2P.fq.gz,./filtered/liver_PP2_f_trimmed_2P.fq.gz,./filtered/liver_PP3_m_trimmed_2P.fq.gz,./filtered/liver_PP4_f_trimmed_2P.fq.gz,./filtered/liver_PP5_m_trimmed_2P.fq.gz,./filtered/liver_PP6_f_trimmed_2P.fq.gz,./filtered/liver_PP7_m_trimmed_2P.fq.gz,./filtered/pec_musAD_PP1_m_trimmed_2P.fq.gz,./filtered/pec_musAD_PP2_f_trimmed_2P.fq.gz,./filtered/pec_musAD_PP3_m_trimmed_2P.fq.gz,./filtered/pec_musAD_PP4_f_trimmed_2P.fq.gz,./filtered/pec_musAD_PP5_m_trimmed_2P.fq.gz,./filtered/pec_musAD_PP6_f_trimmed_2P.fq.gz,./filtered/pec_musAD_PP7_m_trimmed_2P.fq.gz,./filtered/pit_PP1_m_trimmed_2P.fq.gz,./filtered/pit_PP2_f_trimmed_2P.fq.gz,./filtered/pit_PP3_m_trimmed_2P.fq.gz,./filtered/pit_PP4_f_trimmed_2P.fq.gz,./filtered/pit_PP5_trimmed_2P.fq.gz,./filtered/pit_PP6_f_trimmed_2P.fq.gz,./filtered/pit_PP7_m_trimmed_2P.fq.gz \
--CPU 20

