#! /bin/bash
#Run trinity to assemble transcriptome
#Dependency: trinity v2.15.1

TRINITY_SMIG_PATH=/usr/local/biotools/t/trinity:2.15.1--h6ab5fc9_2

singularity exec ${TRINITY_SMIG_PATH} Trinity --seqType fq --max_memory 300G --left \
./filtered/brain_JJ1_m_trimmed_1P.fq.gz,./filtered/brain_JJ2_f_trimmed_1P.fq.gz,./filtered/brain_JJ3_m_trimmed_1P.fq.gz,./filtered/brain_JJ4_f_trimmed_1P.fq.gz,./filtered/brain_JJ5_m_trimmed_1P.fq.gz,./filtered/brain_JJ6_f_trimmed_1P.fq.gz,./filtered/brain_JJ7_m_trimmed_1P.fq.gz,./filtered/gill_JJ1_m_trimmed_1P.fq.gz,./filtered/gill_JJ2_f_trimmed_1P.fq.gz,./filtered/gill_JJ3_m_trimmed_1P.fq.gz,./filtered/gill_JJ4_f_trimmed_1P.fq.gz,./filtered/gill_JJ5_m_trimmed_1P.fq.gz,./filtered/gill_JJ6_f_trimmed_1P.fq.gz,./filtered/gill_JJ7_m_trimmed_1P.fq.gz,./filtered/gonad_JJ1_m_trimmed_1P.fq.gz,./filtered/gonad_JJ2_f_trimmed_1P.fq.gz,./filtered/gonad_JJ3_m_trimmed_1P.fq.gz,./filtered/gonad_JJ4_f_trimmed_1P.fq.gz,./filtered/gonad_JJ5_m_trimmed_1P.fq.gz,./filtered/gonad_JJ6_f_trimmed_1P.fq.gz,./filtered/gonad_JJ7_m_trimmed_1P.fq.gz,./filtered/liver_JJ1_m_trimmed_1P.fq.gz,./filtered/liver_JJ2_f_trimmed_1P.fq.gz,./filtered/liver_JJ3_m_trimmed_1P.fq.gz,./filtered/liver_JJ4_f_trimmed_1P.fq.gz,./filtered/liver_JJ5_m_trimmed_1P.fq.gz,./filtered/liver_JJ6_f_trimmed_1P.fq.gz,./filtered/liver_JJ7_m_trimmed_1P.fq.gz,./filtered/pec_musAD_JJ2_f_trimmed_1P.fq.gz,./filtered/pec_musAD_JJ3_m_trimmed_1P.fq.gz,./filtered/pec_musAD_JJ4_f_trimmed_1P.fq.gz,./filtered/pec_musAD_JJ5_m_trimmed_1P.fq.gz,./filtered/pec_musAD_JJ6_f_trimmed_1P.fq.gz,./filtered/pec_musAD_JJ7_m_trimmed_1P.fq.gz,./filtered/pec_musAD__trimmed_1P.fq.gz,./filtered/pit_JJ1_m_trimmed_1P.fq.gz,./filtered/pit_JJ2_f_trimmed_1P.fq.gz,./filtered/pit_JJ3_m_trimmed_1P.fq.gz,./filtered/pit_JJ4_f_trimmed_1P.fq.gz,./filtered/pit_JJ5_m_trimmed_1P.fq.gz,./filtered/pit_JJ6_f_trimmed_1P.fq.gz,./filtered/pit_JJ7_m_trimmed_1P.fq.gz \
--right ./filtered/brain_JJ1_m_trimmed_2P.fq.gz,./filtered/brain_JJ2_f_trimmed_2P.fq.gz,./filtered/brain_JJ3_m_trimmed_2P.fq.gz,./filtered/brain_JJ4_f_trimmed_2P.fq.gz,./filtered/brain_JJ5_m_trimmed_2P.fq.gz,./filtered/brain_JJ6_f_trimmed_2P.fq.gz,./filtered/brain_JJ7_m_trimmed_2P.fq.gz,./filtered/gill_JJ1_m_trimmed_2P.fq.gz,./filtered/gill_JJ2_f_trimmed_2P.fq.gz,./filtered/gill_JJ3_m_trimmed_2P.fq.gz,./filtered/gill_JJ4_f_trimmed_2P.fq.gz,./filtered/gill_JJ5_m_trimmed_2P.fq.gz,./filtered/gill_JJ6_f_trimmed_2P.fq.gz,./filtered/gill_JJ7_m_trimmed_2P.fq.gz,./filtered/gonad_JJ1_m_trimmed_2P.fq.gz,./filtered/gonad_JJ2_f_trimmed_2P.fq.gz,./filtered/gonad_JJ3_m_trimmed_2P.fq.gz,./filtered/gonad_JJ4_f_trimmed_2P.fq.gz,./filtered/gonad_JJ5_m_trimmed_2P.fq.gz,./filtered/gonad_JJ6_f_trimmed_2P.fq.gz,./filtered/gonad_JJ7_m_trimmed_2P.fq.gz,./filtered/liver_JJ1_m_trimmed_2P.fq.gz,./filtered/liver_JJ2_f_trimmed_2P.fq.gz,./filtered/liver_JJ3_m_trimmed_2P.fq.gz,./filtered/liver_JJ4_f_trimmed_2P.fq.gz,./filtered/liver_JJ5_m_trimmed_2P.fq.gz,./filtered/liver_JJ6_f_trimmed_2P.fq.gz,./filtered/liver_JJ7_m_trimmed_2P.fq.gz,./filtered/pec_musAD_JJ2_f_trimmed_2P.fq.gz,./filtered/pec_musAD_JJ3_m_trimmed_2P.fq.gz,./filtered/pec_musAD_JJ4_f_trimmed_2P.fq.gz,./filtered/pec_musAD_JJ5_m_trimmed_2P.fq.gz,./filtered/pec_musAD_JJ6_f_trimmed_2P.fq.gz,./filtered/pec_musAD_JJ7_m_trimmed_2P.fq.gz,./filtered/pec_musAD__trimmed_2P.fq.gz,./filtered/pit_JJ1_m_trimmed_2P.fq.gz,./filtered/pit_JJ2_f_trimmed_2P.fq.gz,./filtered/pit_JJ3_m_trimmed_2P.fq.gz,./filtered/pit_JJ4_f_trimmed_2P.fq.gz,./filtered/pit_JJ5_m_trimmed_2P.fq.gz,./filtered/pit_JJ6_f_trimmed_2P.fq.gz,./filtered/pit_JJ7_m_trimmed_2P.fq.gz \
--CPU 20
